# Generated by Django 6.0.3 on 2026-05-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECOGIDA', 'Niño recogido en casa'), ('LLEGADA_COLEGIO', 'Llegada al colegio'), ('SALIDA_COLEGIO', 'Salida del colegio'), ('ENTREGA_CASA', 'Niño entregado en casa'), ('PAGO_EXITOSO', 'Pago confirmado'), ('PAGO_FALLIDO', 'Pago fallido'), ('AVISO_GENERAL', 'Aviso general')], max_length=20)),
                ('canal', models.CharField(choices=[('APP', 'Notificación en la app'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Correo electrónico')], default='APP', max_length=10)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada correctamente'), ('FALLIDA', 'Falló el envío'), ('LEIDA', 'Leída por el padre'), ('PENDIENTE', 'Pendiente de envío')], default='PENDIENTE', max_length=10)),
                ('mensaje', models.CharField(max_length=300)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('error_detalle', models.CharField(blank=True, max_length=300, null=True)),
                ('destinatario', models.ForeignKey(limit_choices_to={'rol': 'PADRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
