# Generated by Django 6.0.3 on 2026-04-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=50, null=True)),
                ('mes', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('concepto', models.CharField(blank=True, max_length=500, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cedula_padre', models.ForeignKey(db_column='cedula_padre', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('documento_estudiante', models.ForeignKey(db_column='documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
