# Generated by Django 6.0.3 on 2026-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_options_alter_pago_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado_wompi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_wompi',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id_wompi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
