# Generated by Django 6.0.3 on 2026-04-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CEDULA_CIUDADANIA', 'Cédula de Ciudadanía'), ('CEDULA_EXTRANJERIA', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('TARJETA_IDENTIDAD', 'Tarjeta de Identidad'), ('PERMISO_PROTECCION_TEMPORAL', 'Permiso de Protección Temporal')], max_length=30)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COLEGIO', 'Colegio / Institución'), ('CONDUCTOR', 'Conductor'), ('MONITORA', 'Monitora'), ('PADRE', 'Padre')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
