# Generated by Django 6.0.3 on 2026-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA_CIUDADANIA', 'Cédula de Ciudadanía'), ('CEDULA_EXTRANJERIA', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('TARJETA_IDENTIDAD', 'Tarjeta de Identidad'), ('PERMISO_PROTECCION_TEMPORAL', 'Permiso de Protección Temporal'), ('NIT', 'NIT')], max_length=30),
        ),
    ]
