# Generated by Django 6.0.3 on 2026-06-20 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_acudiente_activo_acudiente_cuenta_activada_and_more'),
        ('rutas', '0003_alter_parada_ruta_alter_paradarecorrido_parada_and_more'),
        ('usuarios', '0003_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RETRASO', 'Retraso en la ruta'), ('AUSENCIA_EST', 'Ausencia de estudiante'), ('FALLA_MECANICA', 'Falla mecánica del vehículo'), ('ACCIDENTE', 'Accidente de tránsito'), ('CLIMA', 'Condiciones climáticas'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta')], default='ACTIVA', max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_registradas', to='usuarios.usuario')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='estudiantes.estudiante')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='rutas.ruta')),
            ],
            options={
                'db_table': 'novedad',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='AusenciaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('razon', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmar'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='estudiantes.estudiante')),
                ('padre', models.ForeignKey(limit_choices_to={'rol': 'PADRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_reportadas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'ausencia_estudiante',
                'ordering': ['-fecha_reporte'],
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
