# Generated by Django 6.0.3 on 2026-04-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('TARJETA_IDENTIDAD', 'Tarjeta de Identidad'), ('CEDULA_CIUDADANIA', 'Cédula de Ciudadanía'), ('CEDULA_EXTRANJERIA', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO_CIVIL', 'Registro Civil'), ('PERMISO_PROTECCION_TEMPORAL', 'Permiso de Protección Temporal')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('grado', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=500, null=True)),
                ('alergias', models.CharField(blank=True, max_length=300, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=300, null=True)),
                ('observaciones_medicas', models.CharField(blank=True, max_length=500, null=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cedula_padre', models.ForeignKey(db_column='cedula_padre', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('codigo_ruta', models.ForeignKey(blank=True, db_column='codigo_ruta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
