# Generated by Django 6.0.3 on 2026-05-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('usuarios', '0002_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_padre',
            field=models.ForeignKey(blank=True, db_column='cedula_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CEDULA_CIUDADANIA', 'Cédula de Ciudadanía'), ('CEDULA_EXTRANJERIA', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('TARJETA_IDENTIDAD', 'Tarjeta de Identidad'), ('PERMISO_PROTECCION_TEMPORAL', 'Permiso de Protección Temporal')], max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acudiente_perfil', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'acudiente',
            },
        ),
        migrations.CreateModel(
            name='EstudianteAcudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('tipo_notificaciones', models.CharField(choices=[('TODAS', 'Todas'), ('CRITICAS', 'Solo críticas')], default='TODAS', max_length=10)),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.acudiente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'estudiante_acudiente',
                'unique_together': {('estudiante', 'acudiente')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='acudientes',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', through='estudiantes.EstudianteAcudiente', to='estudiantes.acudiente'),
        ),
    ]
