# Generated by Django 6.0.3 on 2026-06-19 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_estudiante_cedula_padre_acudiente_and_more'),
        ('usuarios', '0002_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='cuenta_activada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='token_invitacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='usuario',
            field=models.OneToOneField(blank=True, db_column='usuario_cedula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acudiente_perfil', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='estudianteacudiente',
            name='acudiente',
            field=models.ForeignKey(db_column='acudiente', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.acudiente'),
        ),
        migrations.AlterField(
            model_name='estudianteacudiente',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
    ]
