# Generated by Django 6.0.3 on 2026-06-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_acudiente_activo_acudiente_cuenta_activada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='localidad',
            field=models.CharField(blank=True, choices=[('USAQUEN', 'Usaquén'), ('CHAPINERO', 'Chapinero'), ('SANTA_FE', 'Santa Fe'), ('SAN_CRISTOBAL', 'San Cristóbal'), ('USME', 'Usme'), ('TUNJUELITO', 'Tunjuelito'), ('BOSA', 'Bosa'), ('KENNEDY', 'Kennedy'), ('FONTIBON', 'Fontibón'), ('ENGATIVA', 'Engativá'), ('SUBA', 'Suba'), ('BARRIOS_UNIDOS', 'Barrios Unidos'), ('TEUSAQUILLO', 'Teusaquillo'), ('MARTIRES', 'Los Mártires'), ('ANTONIO_NARINO', 'Antonio Nariño'), ('PUENTE_ARANDA', 'Puente Aranda'), ('CANDELARIA', 'La Candelaria'), ('RAFAEL_URIBE', 'Rafael Uribe Uribe'), ('CIUDAD_BOLIVAR', 'Ciudad Bolívar'), ('SUMAPAZ', 'Sumapaz')], max_length=30, null=True),
        ),
    ]
