# Generated by Django 6.0.3 on 2026-05-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=300)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta')),
            ],
            options={
                'db_table': 'parada',
                'ordering': ['ruta', 'orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('lista_confirmada', models.BooleanField(default=False)),
                ('hora_confirmacion_lista', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ultima_ubicacion_actualizada', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorridos_conductor', to='usuarios.usuario')),
                ('monitora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorridos_monitora', to='usuarios.usuario')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='rutas.ruta')),
            ],
            options={
                'db_table': 'recorrido',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRecorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('SALTADA', 'Saltada')], default='PENDIENTE', max_length=15)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos_parada', to='rutas.parada')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_recorrido', to='rutas.recorrido')),
            ],
            options={
                'db_table': 'parada_recorrido',
                'ordering': ['parada__orden'],
                'unique_together': {('recorrido', 'parada')},
            },
        ),
    ]
