# Generated by Django 6.0.3 on 2026-06-19 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_parada_recorrido_paradarecorrido'),
        ('usuarios', '0002_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='ruta',
            field=models.ForeignKey(db_column='ruta', on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='paradarecorrido',
            name='parada',
            field=models.ForeignKey(db_column='parada', on_delete=django.db.models.deletion.CASCADE, related_name='recorridos_parada', to='rutas.parada'),
        ),
        migrations.AlterField(
            model_name='paradarecorrido',
            name='recorrido',
            field=models.ForeignKey(db_column='recorrido', on_delete=django.db.models.deletion.CASCADE, related_name='paradas_recorrido', to='rutas.recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='conductor',
            field=models.ForeignKey(blank=True, db_column='conductor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorridos_conductor', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='monitora',
            field=models.ForeignKey(blank=True, db_column='monitora', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorridos_monitora', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='ruta',
            field=models.ForeignKey(db_column='ruta', on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='rutas.ruta'),
        ),
    ]
