# Generated by Django 6.0.3 on 2026-06-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alter_parada_ruta_alter_paradarecorrido_parada_and_more'),
        ('usuarios', '0004_novedad_ausenciaestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradarecorrido',
            name='monitora_cedula',
            field=models.ForeignKey(blank=True, db_column='monitora_cedula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_monitora', to='usuarios.usuario'),
        ),
    ]
