# Generated by Django 6.0.3 on 2026-06-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alter_parada_ruta_alter_paradarecorrido_parada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='zona',
            field=models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('ORIENTE', 'Oriente'), ('OCCIDENTE', 'Occidente'), ('CENTRO', 'Centro')], max_length=20, null=True),
        ),
    ]
