# Generated by Django 6.0.3 on 2026-06-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_ruta_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana — Recogida hacia el colegio'), ('TARDE', 'Tarde — Entrega a casa')], default='MAÑANA', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='recorrido',
            unique_together={('ruta', 'fecha', 'turno')},
        ),
    ]
