# Generated by Django 6.0.3 on 2026-05-01 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=200)),
                ('tipo_institucion', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('CONCESION', 'Concesión'), ('TECNICA', 'Técnica')], max_length=20)),
                ('codigo_dane', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email_institucional', models.EmailField(max_length=200, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('nombre_rector', models.CharField(max_length=200)),
                ('telefono_rector', models.CharField(blank=True, max_length=20, null=True)),
                ('email_rector', models.EmailField(blank=True, max_length=200, null=True)),
                ('max_rutas', models.IntegerField(default=10)),
                ('max_conductores', models.IntegerField(default=20)),
                ('max_estudiantes', models.IntegerField(default=500)),
                ('plan', models.CharField(choices=[('BASICO', 'Básico'), ('ESTANDAR', 'Estándar'), ('PREMIUM', 'Premium'), ('ILIMITADO', 'Ilimitado')], default='BASICO', max_length=20)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegio_perfil', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'colegio',
                'ordering': ['nombre_institucion'],
            },
        ),
    ]
