# Generated by Django 6.0.3 on 2026-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/'),
        ),
    ]
