# Generated by Django 6.0.3 on 2026-06-19 20:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_colegio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
